imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#        driver:   pdo_pgsql
#        host:     ec2-54-83-29-15.compute-1.amazonaws.com
#        port:     5432
#        dbname:   d2odlqtfjdtd3h
#        user:     eatzgtpnbjjojk
#        password: HGoMDI0LVg9VEi-BpFIqnF2kBm

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console
